language: python

python:
  - 3.8.5

services:
  postgresql
addons:
  postgresql: '9.5'


env:
  global:
    - PIPENV_VIRTUAL_VENV_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - cp contrib/env-sample .env
before_script:
  - psql -c "CREATE DATABASE testdb" -U postgres


script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=projectpro

after_success:
  - pipenv run codecov